---

config:
  install_tree:
    root: ../../site
    projections:
      all: "{architecture.platform}-{architecture.target}/{compiler.name}-{compiler.version}/{name}-{version}-{hash}"
  source_cache: ../../cache

  build_stage::
    - $tempdir/$user/spack-stage
    - $user_cache_path/stage